import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Taskify',
  // TODO: 홈페이지 설명 추가
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>{children}</body>
    </html>
  );
}
